services:
  back:
    image: cannatracker.azurecr.io/cannatracker-back:latest
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - redis-network
  front:
    image: cannatracker.azurecr.io/cannatracker-front:latest
    depends_on:
      - back
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=https://thegreenwizard.live
  redis:
    image: redis:latest
    restart: always
    networks:
      - redis-network
    volumes:
      - redis-volume:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - redis-network
    volumes:
      - redisinsight-volume:/db
#  portainer:
#    image: portainer/portainer-ce:latest
#    ports:
#      - '9443:9443'
#    volumes:
#      - portainer-volume:/data
#      - /var/run/docker.sock:/var/run/docker.sock

networks:
  redis-network:

volumes:
  redis-volume:
  redisinsight-volume:
#  portainer-volume:
